### ISSUE TITLE
README.md aktualisieren

### ISSUE THREAD

**Issue by nOester** [swisstopo/swissgeol-viewer-suite#1343]
**Beschreibung**
Das README.md von https://github.com/swisstopo/swissgeol-viewer-app so aktualisiert werden, dass die Applikation viewer.swissgeol.ch von einem Nutzer mit fortgeschrittenen Kenntnissen installiert und lauffähig gemacht werden kann.  
Zusätzlich soll ein Standard definiert werden, nach dem die READM-md-Files der swissgeol.ch-Applikationen aufgebaut werden.

**ToDos**
- [ ] Prüfen, welche Informationen erforderlich sind, um die Applikation unter Windows, Linux und MacOSX zu installieren
- [ ] Anpassung des README.md mit den relevanten Informationen
- [ ] Definition eines Standards, z.B. in Form eines Templates, für die READM.md-Files

**Acceptance Criteria**
- Das README.md der Applikation viewer.swissgeol.ch ist mit den relevanten Informationen angepasst
- Es liegt ein Standard für die README.md vor

**Hinweis**
Die Arbeiten können von @nOester vorgenommen werden.

**Comment by nOester** [comment]
Grundstruktur eines neuen READE.md erstellt:
https://github.com/swisstopo/swissgeol-viewer-app/blob/feature/viewer-1343-readme-aktualisieren/README-new.md

**Comment by TIL-EBP** [comment]
@daniel-va habs mir eben angeschaut, sieht gut aus für mich. Danke auch fürs nachtragen des CHANGELOGs
